/* Pure-JS QR decoder.
 *
 * Companion to barcode.js. Same reason for existing: BarcodeDetector is
 * Chrome-only, so /floor station and material codes could not be scanned on
 * Firefox, Safari or any iPad, and the operator was pushed to manual entry.
 * Same reason for being vendored rather than fetched: the plant is offline.
 *
 * This is a general decoder, not one tuned to the codes BatchTwin prints.
 * Deliberately so -- a decoder that only reads its own output fails the moment
 * a label is printed at a different size or photographed at an angle.
 *
 *   versions 1-10, all four error-correction levels, all eight masks,
 *   numeric / alphanumeric / byte segments, full Reed-Solomon correction.
 *
 * Verified in tests/test_qr.js against QR symbols generated by segno, an
 * independent implementation, rather than against an encoder of our own.
 */
(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  else root.BTQr = api;
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  /* =============================================================== GF(256) */
  // QR uses the field generated by x^8 + x^4 + x^3 + x^2 + 1 (0x11d).
  const EXP = new Uint8Array(512), LOG = new Uint8Array(256);
  (function initGF() {
    let x = 1;
    for (let i = 0; i < 255; i++) {
      EXP[i] = x;
      LOG[x] = i;
      x <<= 1;
      if (x & 0x100) x ^= 0x11d;
    }
    for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255];
  })();

  const gmul = (a, b) => (a === 0 || b === 0) ? 0 : EXP[LOG[a] + LOG[b]];
  const gdiv = (a, b) => (a === 0) ? 0 : EXP[(LOG[a] + 255 - LOG[b]) % 255];
  const ginv = (a) => EXP[255 - LOG[a]];

  function polyMul(p, q) {
    const r = new Uint8Array(p.length + q.length - 1);
    for (let i = 0; i < p.length; i++) {
      if (!p[i]) continue;
      for (let j = 0; j < q.length; j++) r[i + j] ^= gmul(p[i], q[j]);
    }
    return r;
  }

  function polyEval(p, x) {
    let y = 0;
    for (let i = 0; i < p.length; i++) y = gmul(y, x) ^ p[i];
    return y;
  }

  /* --------------------------------------------------- Reed-Solomon decode */
  /**
   * Correct up to ecLen/2 errors in place.
   * Berlekamp-Massey for the locator, Chien search for positions, Forney for
   * magnitudes. Returns false if the block is beyond repair -- which must be a
   * refusal, never a guess: a silently mis-corrected batch code is worse than
   * no scan at all.
   */
  function rsDecode(msg, ecLen) {
    const synd = new Uint8Array(ecLen);
    let anyError = false;
    for (let i = 0; i < ecLen; i++) {
      synd[i] = polyEval(msg, EXP[i]);
      if (synd[i]) anyError = true;
    }
    if (!anyError) return true;

    // Berlekamp-Massey
    let errLoc = [1], oldLoc = [1];
    for (let i = 0; i < ecLen; i++) {
      oldLoc = oldLoc.concat([0]);
      let delta = synd[i];
      for (let j = 1; j < errLoc.length; j++) {
        delta ^= gmul(errLoc[errLoc.length - 1 - j], synd[i - j]);
      }
      if (delta === 0) continue;
      if (oldLoc.length > errLoc.length) {
        const newLoc = oldLoc.map(c => gmul(c, delta));
        oldLoc = errLoc.map(c => gmul(c, ginv(delta)));
        errLoc = newLoc;
      }
      const scaled = oldLoc.map(c => gmul(c, delta));
      const out = new Array(Math.max(errLoc.length, scaled.length)).fill(0);
      for (let k = 0; k < errLoc.length; k++) out[out.length - errLoc.length + k] ^= errLoc[k];
      for (let k = 0; k < scaled.length; k++) out[out.length - scaled.length + k] ^= scaled[k];
      errLoc = out;
    }
    while (errLoc.length && errLoc[0] === 0) errLoc.shift();
    const nerr = errLoc.length - 1;
    if (nerr * 2 > ecLen || nerr === 0) return false;

    // Chien search: which positions are in error
    const positions = [];
    for (let i = 0; i < msg.length; i++) {
      if (polyEval(errLoc, EXP[255 - i]) === 0) positions.push(msg.length - 1 - i);
    }
    if (positions.length !== nerr) return false;

    // Forney: how wrong each one is
    const syndRev = Array.from(synd).reverse();
    const errEval = polyMul(syndRev, errLoc).slice(-ecLen);
    const coefPos = positions.map(p => msg.length - 1 - p);
    for (let i = 0; i < coefPos.length; i++) {
      const xiInv = ginv(EXP[coefPos[i]]);
      // Forney denominator is Lambda'(Xi^-1), and since
      //   Lambda(x) = prod_j (1 - Xj x)  =>  Lambda'(Xi^-1) = Xi * prod_{j!=i}(...)
      // the Xi cancels against the Xi in the numerator. Carrying it in only one
      // of the two places scales every magnitude by Xi and corrupts the block.
      let denom = 1;
      for (let j = 0; j < coefPos.length; j++) {
        if (j === i) continue;
        denom = gmul(denom, 1 ^ gmul(xiInv, EXP[coefPos[j]]));
      }
      if (denom === 0) return false;
      msg[positions[i]] ^= gdiv(polyEval(errEval, xiInv), denom);
    }

    for (let i = 0; i < ecLen; i++) if (polyEval(msg, EXP[i])) return false;
    return true;
  }

  /* ================================================================ tables */
  // [ecCodewordsPerBlock, [[blockCount, dataCodewords], ...]] per version, per level.
  // Order of levels: L, M, Q, H.
  const RS_BLOCKS = {
    1:  [[7, [[1, 19]]], [10, [[1, 16]]], [13, [[1, 13]]], [17, [[1, 9]]]],
    2:  [[10, [[1, 34]]], [16, [[1, 28]]], [22, [[1, 22]]], [28, [[1, 16]]]],
    3:  [[15, [[1, 55]]], [26, [[1, 44]]], [18, [[2, 17]]], [22, [[2, 13]]]],
    4:  [[20, [[1, 80]]], [18, [[2, 32]]], [26, [[2, 24]]], [16, [[4, 9]]]],
    5:  [[26, [[1, 108]]], [24, [[2, 43]]], [18, [[2, 15], [2, 16]]], [22, [[2, 11], [2, 12]]]],
    6:  [[18, [[2, 68]]], [16, [[4, 27]]], [24, [[4, 19]]], [28, [[4, 15]]]],
    7:  [[20, [[2, 78]]], [18, [[4, 31]]], [18, [[2, 14], [4, 15]]], [26, [[4, 13], [1, 14]]]],
    8:  [[24, [[2, 97]]], [22, [[2, 38], [2, 39]]], [22, [[4, 18], [2, 19]]], [26, [[4, 14], [2, 15]]]],
    9:  [[30, [[2, 116]]], [22, [[3, 36], [2, 37]]], [20, [[4, 16], [4, 17]]], [24, [[4, 12], [4, 13]]]],
    10: [[18, [[2, 68], [2, 69]]], [26, [[4, 43], [1, 44]]], [24, [[6, 19], [2, 20]]], [28, [[6, 15], [2, 16]]]],
  };

  const ALIGN_POS = {
    1: [], 2: [6, 18], 3: [6, 22], 4: [6, 26], 5: [6, 30],
    6: [6, 34], 7: [6, 22, 38], 8: [6, 24, 42], 9: [6, 26, 46], 10: [6, 28, 50],
  };

  // Level bits as they appear in the format information, indexed L,M,Q,H.
  const LEVEL_BITS = [1, 0, 3, 2];

  const MASKS = [
    (i, j) => ((i + j) & 1) === 0,
    (i, j) => (i & 1) === 0,
    (i, j) => j % 3 === 0,
    (i, j) => (i + j) % 3 === 0,
    (i, j) => (((i >> 1) + Math.floor(j / 3)) & 1) === 0,
    (i, j) => ((i * j) & 1) + ((i * j) % 3) === 0,
    (i, j) => (((i * j) & 1) + ((i * j) % 3)) % 2 === 0,
    (i, j) => ((((i + j) & 1) + ((i * j) % 3)) % 2) === 0,
  ];

  /* -------------------------------------------------------- format / version */
  function bchFormat(data) {   // 5 data bits -> 15 bit format, BCH(15,5)
    let d = data << 10;
    for (let i = 4; i >= 0; i--) {
      if (d & (1 << (i + 10))) d ^= 0x537 << i;
    }
    return ((data << 10) | d) ^ 0x5412;
  }

  const FORMAT_TABLE = (function () {
    const t = [];
    for (let d = 0; d < 32; d++) t.push(bchFormat(d));
    return t;
  })();

  const popcount = (x) => { let c = 0; while (x) { c += x & 1; x >>= 1; } return c; };

  /** Nearest valid format word; null if nothing is within 3 bits. */
  function decodeFormat(raw) {
    let best = -1, bestDist = 99;
    for (let d = 0; d < 32; d++) {
      const dist = popcount(raw ^ FORMAT_TABLE[d]);
      if (dist < bestDist) { bestDist = dist; best = d; }
    }
    if (bestDist > 3) return null;
    return { level: LEVEL_BITS.indexOf(best >> 3), mask: best & 7 };
  }

  /* =============================================================== bit grid */
  function isFunctionModule(dim, version, r, c) {
    // finder patterns + separators
    if (r <= 8 && c <= 8) return true;
    if (r <= 8 && c >= dim - 8) return true;
    if (r >= dim - 8 && c <= 8) return true;
    // timing patterns
    if (r === 6 || c === 6) return true;
    // alignment patterns
    const pos = ALIGN_POS[version] || [];
    for (const pr of pos) {
      for (const pc of pos) {
        if ((pr === 6 && pc === 6) ||
            (pr === 6 && pc === pos[pos.length - 1]) ||
            (pr === pos[pos.length - 1] && pc === 6)) continue;
        if (Math.abs(r - pr) <= 2 && Math.abs(c - pc) <= 2) return true;
      }
    }
    // version information blocks (version >= 7)
    if (version >= 7) {
      if (c < 6 && r >= dim - 11 && r < dim - 8) return true;
      if (r < 6 && c >= dim - 11 && c < dim - 8) return true;
    }
    return false;
  }

  /** Read the interleaved codewords out of the matrix in the standard zigzag. */
  function readCodewords(get, dim, version, mask) {
    const maskFn = MASKS[mask];
    const out = [];
    let byte = 0, bits = 0, up = true;
    for (let right = dim - 1; right >= 1; right -= 2) {
      if (right === 6) right = 5;    // the vertical timing column is skipped
      for (let v = 0; v < dim; v++) {
        const r = up ? dim - 1 - v : v;
        for (let k = 0; k < 2; k++) {
          const c = right - k;
          if (isFunctionModule(dim, version, r, c)) continue;
          let bit = get(r, c) ? 1 : 0;
          if (maskFn(r, c)) bit ^= 1;
          byte = (byte << 1) | bit;
          if (++bits === 8) { out.push(byte); byte = 0; bits = 0; }
        }
      }
      up = !up;
    }
    return out;
  }

  /** Undo block interleaving and run Reed-Solomon over each block. */
  function correctBlocks(codewords, version, level) {
    const [ecLen, groups] = RS_BLOCKS[version][level];
    const blocks = [];
    for (const [count, dataLen] of groups) {
      for (let i = 0; i < count; i++) blocks.push({ dataLen, data: [] });
    }
    const total = blocks.reduce((a, b) => a + b.dataLen, 0);
    if (codewords.length < total + blocks.length * ecLen) return null;

    // data codewords are interleaved across blocks, short blocks first
    const maxData = Math.max(...blocks.map(b => b.dataLen));
    let p = 0;
    for (let i = 0; i < maxData; i++) {
      for (const b of blocks) {
        if (i < b.dataLen) b.data.push(codewords[p++]);
      }
    }
    for (let i = 0; i < ecLen; i++) {
      for (const b of blocks) {
        if (!b.ec) b.ec = [];
        b.ec.push(codewords[p++]);
      }
    }

    const out = [];
    for (const b of blocks) {
      const full = Uint8Array.from(b.data.concat(b.ec));
      if (!rsDecode(full, ecLen)) return null;
      for (let i = 0; i < b.dataLen; i++) out.push(full[i]);
    }
    return out;
  }

  /* ---------------------------------------------------------- bit stream */
  const ALNUM = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ $%*+-./:";

  function decodeBits(data, version) {
    let pos = 0;
    const total = data.length * 8;
    const read = (n) => {
      let v = 0;
      for (let i = 0; i < n; i++) {
        if (pos >= total) throw new Error("truncated");
        const bit = (data[pos >> 3] >> (7 - (pos & 7))) & 1;
        v = (v << 1) | bit;
        pos++;
      }
      return v;
    };
    const countBits = (mode) => {
      if (version <= 9) return mode === 1 ? 10 : mode === 2 ? 9 : 8;
      if (version <= 26) return mode === 1 ? 12 : mode === 2 ? 11 : 16;
      return mode === 1 ? 14 : mode === 2 ? 13 : 16;
    };

    const bytes = [];
    let text = "";
    while (pos + 4 <= total) {
      const mode = read(4);
      if (mode === 0) break;                      // terminator
      if (mode === 7) { read(8); continue; }      // ECI: assume UTF-8 and move on
      if (mode !== 1 && mode !== 2 && mode !== 4) throw new Error("mode " + mode);
      const n = read(countBits(mode));
      if (mode === 1) {
        for (let i = 0; i < n;) {
          const take = Math.min(3, n - i);
          const v = read(take === 3 ? 10 : take === 2 ? 7 : 4);
          text += String(v).padStart(take, "0");
          i += take;
        }
      } else if (mode === 2) {
        for (let i = 0; i < n;) {
          if (n - i >= 2) {
            const v = read(11);
            text += ALNUM[Math.floor(v / 45)] + ALNUM[v % 45];
            i += 2;
          } else {
            text += ALNUM[read(6)];
            i += 1;
          }
        }
      } else {
        for (let i = 0; i < n; i++) bytes.push(read(8));
        text += null;   // placeholder, replaced below
        text = text.slice(0, -4);
      }
    }
    if (bytes.length) {
      // Byte mode is UTF-8 in practice; fall back to latin-1 if it is not valid.
      try {
        if (typeof TextDecoder !== "undefined") {
          return text + new TextDecoder("utf-8", {fatal: true})
            .decode(Uint8Array.from(bytes));
        }
      } catch (e) { /* not utf-8 */ }
      return text + bytes.map(b => String.fromCharCode(b)).join("");
    }
    return text;
  }

  /* ============================================================= geometry */
  function PerspectiveTransform(a11, a21, a31, a12, a22, a32, a13, a23, a33) {
    this.a11 = a11; this.a21 = a21; this.a31 = a31;
    this.a12 = a12; this.a22 = a22; this.a32 = a32;
    this.a13 = a13; this.a23 = a23; this.a33 = a33;
  }
  PerspectiveTransform.prototype.map = function (x, y) {
    const d = this.a13 * x + this.a23 * y + this.a33;
    return [(this.a11 * x + this.a21 * y + this.a31) / d,
            (this.a12 * x + this.a22 * y + this.a32) / d];
  };
  PerspectiveTransform.prototype.times = function (o) {
    return new PerspectiveTransform(
      this.a11 * o.a11 + this.a21 * o.a12 + this.a31 * o.a13,
      this.a11 * o.a21 + this.a21 * o.a22 + this.a31 * o.a23,
      this.a11 * o.a31 + this.a21 * o.a32 + this.a31 * o.a33,
      this.a12 * o.a11 + this.a22 * o.a12 + this.a32 * o.a13,
      this.a12 * o.a21 + this.a22 * o.a22 + this.a32 * o.a23,
      this.a12 * o.a31 + this.a22 * o.a32 + this.a32 * o.a33,
      this.a13 * o.a11 + this.a23 * o.a12 + this.a33 * o.a13,
      this.a13 * o.a21 + this.a23 * o.a22 + this.a33 * o.a23,
      this.a13 * o.a31 + this.a23 * o.a32 + this.a33 * o.a33);
  };

  function squareToQuad(x0, y0, x1, y1, x2, y2, x3, y3) {
    const dx3 = x0 - x1 + x2 - x3, dy3 = y0 - y1 + y2 - y3;
    if (dx3 === 0 && dy3 === 0) {
      return new PerspectiveTransform(x1 - x0, x2 - x1, x0, y1 - y0, y2 - y1, y0, 0, 0, 1);
    }
    const dx1 = x1 - x2, dx2 = x3 - x2, dy1 = y1 - y2, dy2 = y3 - y2;
    const den = dx1 * dy2 - dx2 * dy1;
    const a13 = (dx3 * dy2 - dx2 * dy3) / den;
    const a23 = (dx1 * dy3 - dx3 * dy1) / den;
    return new PerspectiveTransform(
      x1 - x0 + a13 * x1, x3 - x0 + a23 * x3, x0,
      y1 - y0 + a13 * y1, y3 - y0 + a23 * y3, y0,
      a13, a23, 1);
  }

  function quadToSquare(x0, y0, x1, y1, x2, y2, x3, y3) {
    const s = squareToQuad(x0, y0, x1, y1, x2, y2, x3, y3);
    // adjugate
    return new PerspectiveTransform(
      s.a22 * s.a33 - s.a23 * s.a32, s.a23 * s.a31 - s.a21 * s.a33,
      s.a21 * s.a32 - s.a22 * s.a31,
      s.a13 * s.a32 - s.a12 * s.a33, s.a11 * s.a33 - s.a13 * s.a31,
      s.a12 * s.a31 - s.a11 * s.a32,
      s.a12 * s.a23 - s.a13 * s.a22, s.a13 * s.a21 - s.a11 * s.a23,
      s.a11 * s.a22 - s.a12 * s.a21);
  }

  function quadToQuad(sx0, sy0, sx1, sy1, sx2, sy2, sx3, sy3,
                      dx0, dy0, dx1, dy1, dx2, dy2, dx3, dy3) {
    return squareToQuad(dx0, dy0, dx1, dy1, dx2, dy2, dx3, dy3)
      .times(quadToSquare(sx0, sy0, sx1, sy1, sx2, sy2, sx3, sy3));
  }

  /* ------------------------------------------------------ finder patterns */
  /**
   * Locate the three 1:1:3:1:1 finder patterns.
   * Rows are scanned for the ratio, then each hit is confirmed vertically, which
   * is what keeps printed text and crate edges from registering as corners.
   */
  function findFinders(bits, w, h) {
    const hits = [];
    const check = (counts) => {
      const total = counts.reduce((a, b) => a + b, 0);
      if (total < 7) return false;
      const unit = total / 7;
      const tol = unit * 0.65;
      return Math.abs(unit - counts[0]) < tol && Math.abs(unit - counts[1]) < tol &&
             Math.abs(3 * unit - counts[2]) < 3 * tol &&
             Math.abs(unit - counts[3]) < tol && Math.abs(unit - counts[4]) < tol;
    };
    const at = (x, y) => (x < 0 || y < 0 || x >= w || y >= h) ? 0 : bits[y * w + x];

    // vertical confirmation through a candidate centre
    const vcheck = (cx, cy) => {
      const counts = [0, 0, 0, 0, 0];
      let y = cy;
      while (y >= 0 && at(cx, y)) { counts[2]++; y--; }
      while (y >= 0 && !at(cx, y)) { counts[1]++; y--; }
      while (y >= 0 && at(cx, y)) { counts[0]++; y--; }
      y = cy + 1;
      while (y < h && at(cx, y)) { counts[2]++; y++; }
      while (y < h && !at(cx, y)) { counts[3]++; y++; }
      while (y < h && at(cx, y)) { counts[4]++; y++; }
      return check(counts) ? counts : null;
    };

    for (let y = 0; y < h; y++) {
      const counts = [0, 0, 0, 0, 0];
      let state = 0;
      for (let x = 0; x < w; x++) {
        if (at(x, y)) {                 // dark
          if (state & 1) state++;       // was counting light, now a dark run
          counts[state]++;
        } else {                        // light
          if ((state & 1) === 0) {      // was counting dark
            if (state === 4) {
              // The five runs are complete: this is where a candidate is judged.
              if (check(counts)) {
                const total = counts.reduce((a, b) => a + b, 0);
                const cx = Math.round(x - counts[4] - counts[3] - counts[2] / 2);
                if (vcheck(cx, y)) hits.push({ x: cx, y, size: total / 7 });
              }
              // Slide the window back two runs: the last dark/light/dark may be
              // the start of the next pattern.
              counts[0] = counts[2]; counts[1] = counts[3]; counts[2] = counts[4];
              counts[3] = 1; counts[4] = 0;
              state = 3;
            } else {
              counts[++state]++;
            }
          } else {
            counts[state]++;
          }
        }
      }
    }

    // cluster nearby hits into single centres
    const centres = [];
    for (const p of hits) {
      let merged = false;
      for (const c of centres) {
        if (Math.abs(c.x - p.x) <= c.size * 2 && Math.abs(c.y - p.y) <= c.size * 2) {
          c.x = (c.x * c.n + p.x) / (c.n + 1);
          c.y = (c.y * c.n + p.y) / (c.n + 1);
          c.size = (c.size * c.n + p.size) / (c.n + 1);
          c.n++; merged = true; break;
        }
      }
      if (!merged) centres.push({ x: p.x, y: p.y, size: p.size, n: 1 });
    }
    return centres.filter(c => c.n >= 2).sort((a, b) => b.n - a.n);
  }

  /** Decide which finder is which corner using the right angle at top-left. */
  function orderFinders(a, b, c) {
    const d = (p, q) => (p.x - q.x) ** 2 + (p.y - q.y) ** 2;
    const ab = d(a, b), bc = d(b, c), ac = d(a, c);
    let tl, p1, p2;
    if (bc >= ab && bc >= ac) { tl = a; p1 = b; p2 = c; }
    else if (ac >= ab && ac >= bc) { tl = b; p1 = a; p2 = c; }
    else { tl = c; p1 = a; p2 = b; }
    // Handedness, in image coordinates where y grows downward: if p1 is the
    // true top-right then tl->p1 points right and tl->p2 points down, and their
    // cross product is positive. (Getting this backwards transposes the symbol
    // and every sampled module lands on the wrong side of the diagonal.)
    const cross = (p1.x - tl.x) * (p2.y - tl.y) - (p1.y - tl.y) * (p2.x - tl.x);
    return cross > 0 ? { tl, tr: p1, bl: p2 } : { tl, tr: p2, bl: p1 };
  }

  /* ------------------------------------------------------------- sampling */
  function sampleGrid(bits, w, h, tf, dim) {
    const grid = new Uint8Array(dim * dim);
    for (let r = 0; r < dim; r++) {
      for (let c = 0; c < dim; c++) {
        const [x, y] = tf.map(c + 0.5, r + 0.5);
        const xi = Math.round(x), yi = Math.round(y);
        if (xi < 0 || yi < 0 || xi >= w || yi >= h) return null;
        grid[r * dim + c] = bits[yi * w + xi];
      }
    }
    return grid;
  }

  function findAlignment(bits, w, h, ex, ey, modSize) {
    // Search a small window for the 1:1:1 dark/light/dark centre.
    const rad = Math.ceil(modSize * 4);
    const at = (x, y) => (x < 0 || y < 0 || x >= w || y >= h) ? 0 : bits[y * w + x];
    let best = null, bestD = Infinity;
    for (let y = Math.round(ey - rad); y <= ey + rad; y++) {
      for (let x = Math.round(ex - rad); x <= ex + rad; x++) {
        if (!at(x, y)) continue;
        // centre module is dark, ring around it light, ring outside dark
        const m = Math.max(1, Math.round(modSize));
        if (at(x - m, y) || at(x + m, y) || at(x, y - m) || at(x, y + m)) continue;
        if (!at(x - 2 * m, y) || !at(x + 2 * m, y) || !at(x, y - 2 * m) || !at(x, y + 2 * m)) continue;
        const d = (x - ex) ** 2 + (y - ey) ** 2;
        if (d < bestD) { bestD = d; best = { x, y }; }
      }
    }
    return best;
  }

  /* ------------------------------------------------------------ binarise */
  /**
   * Local (block) thresholding. A single global threshold loses a QR printed on
   * a curved bottle or lit from one side, which is the normal case on a floor.
   */
  function binarize(luma, w, h) {
    const BS = 16;
    const bw = Math.max(1, Math.ceil(w / BS)), bh = Math.max(1, Math.ceil(h / BS));
    const means = new Float32Array(bw * bh);
    for (let by = 0; by < bh; by++) {
      for (let bx = 0; bx < bw; bx++) {
        let sum = 0, n = 0, mn = 255, mx = 0;
        for (let y = by * BS; y < Math.min(h, (by + 1) * BS); y++) {
          for (let x = bx * BS; x < Math.min(w, (bx + 1) * BS); x++) {
            const v = luma[y * w + x];
            sum += v; n++;
            if (v < mn) mn = v;
            if (v > mx) mx = v;
          }
        }
        // Flat block: bias toward light so blank paper does not become noise.
        means[by * bw + bx] = (mx - mn > 24) ? sum / n : Math.max(0, mn - 1);
      }
    }
    const bits = new Uint8Array(w * h);
    for (let y = 0; y < h; y++) {
      const by = Math.min(bh - 1, y / BS | 0);
      for (let x = 0; x < w; x++) {
        const bx = Math.min(bw - 1, x / BS | 0);
        // average the 3x3 neighbourhood of block means for a smooth threshold
        let t = 0, n = 0;
        for (let j = -1; j <= 1; j++) {
          for (let i = -1; i <= 1; i++) {
            const yy = by + j, xx = bx + i;
            if (yy >= 0 && yy < bh && xx >= 0 && xx < bw) { t += means[yy * bw + xx]; n++; }
          }
        }
        bits[y * w + x] = luma[y * w + x] < (t / n) ? 1 : 0;
      }
    }
    return bits;
  }

  /* ================================================================= entry */
  /** Decode from an already-binarised grid of modules (used by tests). */
  function decodeMatrix(get, dim) {
    if (dim < 21 || (dim - 17) % 4 !== 0) return null;
    const version = (dim - 17) / 4;
    if (!RS_BLOCKS[version]) return null;

    // format information, primary copy then the redundant one
    let raw = 0;
    for (let i = 0; i <= 5; i++) raw = (raw << 1) | get(8, i);
    raw = (raw << 1) | get(8, 7);
    raw = (raw << 1) | get(8, 8);
    raw = (raw << 1) | get(7, 8);
    for (let i = 5; i >= 0; i--) raw = (raw << 1) | get(i, 8);
    let fmt = decodeFormat(raw);
    if (!fmt) {
      let raw2 = 0;
      for (let i = 0; i < 8; i++) raw2 = (raw2 << 1) | get(dim - 1 - i, 8);
      for (let i = 0; i < 7; i++) raw2 = (raw2 << 1) | get(8, dim - 7 + i);
      fmt = decodeFormat(raw2);
    }
    if (!fmt) return null;

    const words = readCodewords(get, dim, version, fmt.mask);
    const data = correctBlocks(words, version, fmt.level);
    if (!data) return null;
    try { return decodeBits(data, version); } catch (e) { return null; }
  }

  function decodeBits2D(bits, w, h) {
    const finders = findFinders(bits, w, h);
    if (finders.length < 3) return null;

    // try the strongest few triples -- printed logos occasionally look like a finder
    const tries = [];
    const n = Math.min(finders.length, 5);
    for (let i = 0; i < n; i++)
      for (let j = i + 1; j < n; j++)
        for (let k = j + 1; k < n; k++) tries.push([finders[i], finders[j], finders[k]]);

    for (const [a, b, c] of tries) {
      const { tl, tr, bl } = orderFinders(a, b, c);
      const modSize = (tl.size + tr.size + bl.size) / 3;
      if (modSize < 1) continue;
      const dist = Math.hypot(tr.x - tl.x, tr.y - tl.y);
      let dim = Math.round(dist / modSize) + 7;
      dim += (4 - ((dim - 17) % 4)) % 4;         // snap to a legal 4v+17
      if (dim < 21 || dim > 57) continue;
      const version = (dim - 17) / 4;
      if (!RS_BLOCKS[version]) continue;

      // Fourth corner. Start from the parallelogram estimate, then, if this
      // version has an alignment pattern, look for it where a preliminary
      // transform says it should be and use that instead -- it is measured
      // rather than extrapolated, so it also absorbs perspective.
      let bx = tr.x + bl.x - tl.x, by = tr.y + bl.y - tl.y;
      let srcBR = dim - 3.5;
      const pos = ALIGN_POS[version];
      if (pos.length) {
        const prelim = quadToQuad(
          3.5, 3.5, dim - 3.5, 3.5, dim - 3.5, dim - 3.5, 3.5, dim - 3.5,
          tl.x, tl.y, tr.x, tr.y, bx, by, bl.x, bl.y);
        const [ex, ey] = prelim.map(dim - 6.5, dim - 6.5);
        const a3 = findAlignment(bits, w, h, ex, ey, modSize);
        if (a3) { bx = a3.x; by = a3.y; srcBR = dim - 6.5; }
      }

      const tf = quadToQuad(
        3.5, 3.5, dim - 3.5, 3.5, srcBR, srcBR, 3.5, dim - 3.5,
        tl.x, tl.y, tr.x, tr.y, bx, by, bl.x, bl.y);
      const grid = sampleGrid(bits, w, h, tf, dim);
      if (!grid) continue;
      const res = decodeMatrix((r, cc) => grid[r * dim + cc], dim);
      if (res !== null) return res;
    }
    return null;
  }

  /** Decode from an ImageData-shaped object. */
  function decodeImageData(img) {
    const { data, width: w, height: h } = img;
    const luma = new Uint8Array(w * h);
    for (let i = 0, o = 0; i < luma.length; i++, o += 4) {
      luma[i] = (data[o] * 77 + data[o + 1] * 150 + data[o + 2] * 29) >> 8;
    }
    return decodeBits2D(binarize(luma, w, h), w, h);
  }

  return {
    decodeImageData, decodeMatrix, decodeBits2D, binarize,
    rsDecode, decodeFormat, findFinders, orderFinders, supported: true,
  };
});
