/* Headless tests for the vendored QR decoder.
 *
 *   node tests/test_qr.js
 *
 * Fixtures in tests/fixtures/qr_cases.json are generated by segno (Python), an
 * independent implementation. Decoding our own encoder's output would only
 * prove the two agree with each other; decoding segno's output proves we agree
 * with the standard.
 *
 * Regenerate fixtures with tests/make_qr_fixtures.py after changing /api/qr.
 */
"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const QR = require("../frontend/qr.js");

const CASES = JSON.parse(
  fs.readFileSync(path.join(__dirname, "fixtures", "qr_cases.json"), "utf8"));

let passed = 0, failed = 0;
function test(name, fn) {
  try { fn(); passed++; console.log("  ok   " + name); }
  catch (e) { failed++; console.log("  FAIL " + name + "\n       " + e.message); }
}

/* ------------------------------------------------------------- rendering */
/** Render a module matrix to an ImageData-shaped object. */
function render(matrix, {scale = 4, border = 4, dark = 25, light = 235,
                         rotate = 0} = {}) {
  const dim = matrix.length;
  const side = (dim + border * 2) * scale;
  let w = side, h = side;
  const px = new Uint8ClampedArray(w * h * 4).fill(255);
  const put = (x, y, v) => {
    const o = (y * w + x) * 4;
    px[o] = px[o + 1] = px[o + 2] = v; px[o + 3] = 255;
  };
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) put(x, y, light);
  for (let r = 0; r < dim; r++) {
    for (let c = 0; c < dim; c++) {
      if (!matrix[r][c]) continue;
      for (let dy = 0; dy < scale; dy++) {
        for (let dx = 0; dx < scale; dx++) {
          put((c + border) * scale + dx, (r + border) * scale + dy, dark);
        }
      }
    }
  }
  let img = {data: px, width: w, height: h};
  for (let i = 0; i < ((rotate / 90) | 0) % 4; i++) img = rot90(img);
  return img;
}

function rot90(img) {
  const {data, width: w, height: h} = img;
  const nw = h, nh = w;
  const out = new Uint8ClampedArray(nw * nh * 4);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const o = (y * w + x) * 4;
      const nx = h - 1 - y, ny = x;
      const no = (ny * nw + nx) * 4;
      out[no] = data[o]; out[no + 1] = data[o + 1];
      out[no + 2] = data[o + 2]; out[no + 3] = 255;
    }
  }
  return {data: out, width: nw, height: nh};
}

function blurImg(img, radius) {
  const {data, width: w, height: h} = img;
  const out = new Uint8ClampedArray(data.length);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      let sum = 0, n = 0;
      for (let j = -radius; j <= radius; j++) {
        for (let i = -radius; i <= radius; i++) {
          const yy = y + j, xx = x + i;
          if (yy < 0 || xx < 0 || yy >= h || xx >= w) continue;
          sum += data[(yy * w + xx) * 4]; n++;
        }
      }
      const o = (y * w + x) * 4;
      out[o] = out[o + 1] = out[o + 2] = Math.round(sum / n); out[o + 3] = 255;
    }
  }
  return {data: out, width: w, height: h};
}

function noisyImg(img, amp, seed) {
  let s = seed || 1;
  const rnd = () => (s = (s * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff;
  const {data, width: w, height: h} = img;
  const out = new Uint8ClampedArray(data.length);
  for (let i = 0; i < w * h; i++) {
    const o = i * 4;
    const v = Math.max(0, Math.min(255, data[o] + (rnd() - 0.5) * 2 * amp));
    out[o] = out[o + 1] = out[o + 2] = v; out[o + 3] = 255;
  }
  return {data: out, width: w, height: h};
}

/** Uneven lighting: a linear brightness ramp across the frame. */
function shade(img, drop) {
  const {data, width: w, height: h} = img;
  const out = new Uint8ClampedArray(data.length);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const o = (y * w + x) * 4;
      const f = 1 - drop * (x / w);
      const v = Math.max(0, Math.min(255, data[o] * f));
      out[o] = out[o + 1] = out[o + 2] = v; out[o + 3] = 255;
    }
  }
  return {data: out, width: w, height: h};
}

/* ------------------------------------------------------- matrix-level */
console.log("\ndecoding the module matrix directly (no image pipeline)");

for (const c of CASES) {
  test(`v${c.version} ecc=${c.error.toUpperCase()} mask=${c.mask}  ${JSON.stringify(c.data).slice(0, 34)}`, () => {
    const got = QR.decodeMatrix((r, col) => c.matrix[r][col], c.dim);
    assert.strictEqual(got, c.data);
  });
}

/* --------------------------------------------------------- image-level */
console.log("\ndecoding rendered images");

for (const c of CASES.slice(0, 9)) {
  test(`rendered  ${JSON.stringify(c.data).slice(0, 34)}`, () => {
    assert.strictEqual(QR.decodeImageData(render(c.matrix)), c.data);
  });
}

test("larger symbol (v4 URL) from an image", () => {
  const c = CASES.find(x => x.version === 4);
  assert.strictEqual(QR.decodeImageData(render(c.matrix, {scale: 5})), c.data);
});

test("UTF-8 byte mode survives the round trip", () => {
  const c = CASES.find(x => /contr/.test(x.data));
  assert.strictEqual(QR.decodeImageData(render(c.matrix, {scale: 5})), c.data);
});

console.log("\nrealistic camera conditions");

const S = CASES[1];   // BT:ST:pesee

test("rotated 90°", () => {
  assert.strictEqual(QR.decodeImageData(render(S.matrix, {rotate: 90})), S.data);
});
test("rotated 180°", () => {
  assert.strictEqual(QR.decodeImageData(render(S.matrix, {rotate: 180})), S.data);
});
test("rotated 270°", () => {
  assert.strictEqual(QR.decodeImageData(render(S.matrix, {rotate: 270})), S.data);
});
test("held close (scale 9)", () => {
  assert.strictEqual(QR.decodeImageData(render(S.matrix, {scale: 9})), S.data);
});
test("held far (scale 3)", () => {
  assert.strictEqual(QR.decodeImageData(render(S.matrix, {scale: 3})), S.data);
});
test("out of focus", () => {
  assert.strictEqual(
    QR.decodeImageData(blurImg(render(S.matrix, {scale: 6}), 2)), S.data);
});
test("sensor noise", () => {
  assert.strictEqual(
    QR.decodeImageData(noisyImg(render(S.matrix, {scale: 6}), 34, 11)), S.data);
});
test("uneven lighting across the frame", () => {
  assert.strictEqual(
    QR.decodeImageData(shade(render(S.matrix, {scale: 6}), 0.45)), S.data);
});
test("low contrast (grey on grey)", () => {
  assert.strictEqual(
    QR.decodeImageData(render(S.matrix, {scale: 6, dark: 95, light: 170})), S.data);
});
test("tight quiet zone", () => {
  assert.strictEqual(QR.decodeImageData(render(S.matrix, {border: 2})), S.data);
});

console.log("\nerror correction actually corrects");

test("a damaged symbol is still recovered", () => {
  const m = CASES.find(x => x.error === "h");   // high ECC, most redundancy
  const mat = m.matrix.map(r => r.slice());
  // wreck a patch in the data region, away from the finders
  for (let r = 12; r < 17; r++) for (let c = 12; c < 17; c++) mat[r][c] ^= 1;
  assert.strictEqual(QR.decodeMatrix((r, c) => mat[r][c], m.dim), m.data);
});

test("damage beyond the correction budget is refused, not guessed", () => {
  const m = CASES[0];
  const mat = m.matrix.map(r => r.slice());
  for (let r = 9; r < 21; r++) for (let c = 0; c < 21; c++) mat[r][c] ^= (r * c) & 1;
  const got = QR.decodeMatrix((r, c) => mat[r][c], m.dim);
  assert.ok(got === null || got === m.data, "returned a fabricated payload: " + got);
});

console.log("\nrefusing to guess");

test("blank frame returns null", () => {
  const w = 200, h = 200;
  const data = new Uint8ClampedArray(w * h * 4).fill(230);
  for (let i = 3; i < data.length; i += 4) data[i] = 255;
  assert.strictEqual(QR.decodeImageData({data, width: w, height: h}), null);
});

test("random noise returns null", () => {
  const w = 220, h = 220;
  const img = noisyImg({data: new Uint8ClampedArray(w * h * 4).fill(128),
                        width: w, height: h}, 127, 5);
  assert.strictEqual(QR.decodeImageData(img), null);
});

test("a barcode is not mistaken for a QR", () => {
  const w = 300, h = 120;
  const data = new Uint8ClampedArray(w * h * 4).fill(255);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const v = (x > 40 && x < 260 && ((x / 3) | 0) % 2 === 0) ? 30 : 235;
      const o = (y * w + x) * 4;
      data[o] = data[o + 1] = data[o + 2] = v; data[o + 3] = 255;
    }
  }
  assert.strictEqual(QR.decodeImageData({data, width: w, height: h}), null);
});

console.log("\nthe payloads /floor actually prints");

for (const c of CASES.filter(x => x.data.startsWith("BT:"))) {
  test(`floor code ${c.data}`, () => {
    assert.strictEqual(QR.decodeImageData(render(c.matrix, {scale: 5})), c.data);
  });
}

console.log(`\n${passed} passed, ${failed} failed\n`);
process.exit(failed ? 1 : 0);
